[build]
  command = "pnpm run build"
  publish = ".next"

[functions]
  included_files = ["next.config.js"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true 